version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - app-network

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: net_protect_backend
    ports:
      - "5555:3000"
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://root:example@mongodb:27017/mydatabase?authSource=admin
    networks:
      - app-network

volumes:
  mongodb_data:


networks:
  app-network:
    driver: bridge